//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user1
    {
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string pername { get; set; }
        public int userId { get; set; }
    }
}
